In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from  sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [2]:
df=pd.read_csv('C://Users//HP//Documents//cardio...csv')

In [3]:
df.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0   
1   1  20228       1     156    85.0    140     90            3     1      0   
2   2  18857       1     165    64.0    130     70            3     1      0   
3   3  17623       2     169    82.0    150    100            1     1      0   
4   4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  newage  
0   0.0       1       0      73  
1   0.0       1       1      68  
2   0.0       0       1      72  
3   0.0       1       1      75  
4   0.0       0       0      76

In [4]:
df.corr()

id       age    gender    height    weight     ap_hi  \
id           1.000000  0.003457  0.003502 -0.003038 -0.001830  0.003356   
age          0.003457  1.000000 -0.022811 -0.081515  0.053684  0.020764   
gender       0.003502 -0.022811  1.000000  0.499033  0.155406  0.006005   
height      -0.003038 -0.081515  0.499033  1.000000  0.290968  0.005488   
weight      -0.001830  0.053684  0.155406  0.290968  1.000000  0.030702   
ap_hi        0.003356  0.020764  0.006005  0.005488  0.030702  1.000000   
ap_lo       -0.002529  0.017647  0.015254  0.006150  0.043710  0.016086   
cholesterol  0.006106  0.154424 -0.035821 -0.050226  0.141768  0.023778   
gluc         0.002467  0.098703 -0.020491 -0.018595  0.106857  0.011841   
smoke       -0.003699 -0.047633  0.338135  0.187989  0.067780 -0.000922   
alco         0.001204 -0.029719  0.170973  0.094426  0.067119  0.001408   
active       0.003755 -0.009927  0.005866 -0.006570 -0.016867 -0.000033   
cardio       0.003799  0.238159  0.008109 -0.010821  0.181660  0.054475   
newage      -0.003647 -0.999089  0.022905  0.081455 -0.053691 -0.020872   

                ap_lo  cholesterol      gluc     smoke      alco    active  \
id          -0.002529     0.006106  0.002467 -0.003699  0.001204  0.003755   
age          0.017647     0.154424  0.098703 -0.047633 -0.029719 -0.009927   
gender       0.015254    -0.035821 -0.020491  0.338135  0.170973  0.005866   
height       0.006150    -0.050226 -0.018595  0.187989  0.094426 -0.006570   
weight       0.043710     0.141768  0.106857  0.067780  0.067119 -0.016867   
ap_hi        0.016086     0.023778  0.011841 -0.000922  0.001408 -0.000033   
ap_lo        1.000000     0.024019  0.010806  0.005186  0.010601  0.004780   
cholesterol  0.024019     1.000000  0.451578  0.010354  0.035770  0.009911   
gluc         0.010806     0.451578  1.000000 -0.004756  0.011257 -0.006770   
smoke        0.005186     0.010354 -0.004756  1.000000  0.340093  0.025858   
alco         0.010601     0.035770  0.011257  0.340093  1.000000  0.025478   
active       0.004780     0.009911 -0.006770  0.025858  0.025478  1.000000   
cardio       0.065719     0.221147  0.089307 -0.015486 -0.007327 -0.035653   
newage      -0.017605    -0.154228 -0.098718  0.047593  0.029728  0.009820   

               cardio    newage  
id           0.003799 -0.003647  
age          0.238159 -0.999089  
gender       0.008109  0.022905  
height      -0.010821  0.081455  
weight       0.181660 -0.053691  
ap_hi        0.054475 -0.020872  
ap_lo        0.065719 -0.017605  
cholesterol  0.221147 -0.154228  
gluc         0.089307 -0.098718  
smoke       -0.015486  0.047593  
alco        -0.007327  0.029728  
active      -0.035653  0.009820  
cardio       1.000000 -0.238143  
newage      -0.238143  1.000000

In [5]:
df.describe()

id           age        gender        height        weight  \
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000   
mean   49972.419900  19468.865814      1.349571    164.359229     74.205690   
std    28851.302323   2467.251667      0.476838      8.210126     14.395757   
min        0.000000  10798.000000      1.000000     55.000000     10.000000   
25%    25006.750000  17664.000000      1.000000    159.000000     65.000000   
50%    50001.500000  19703.000000      1.000000    165.000000     72.000000   
75%    74889.250000  21327.000000      2.000000    170.000000     82.000000   
max    99999.000000  23713.000000      2.000000    250.000000    200.000000   

              ap_hi         ap_lo   cholesterol          gluc         smoke  \
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000   
mean     128.817286     96.630414      1.366871      1.226457      0.088129   
std      154.011419    188.472530      0.680250      0.572270      0.283484   
min     -150.000000    -70.000000      1.000000      1.000000      0.000000   
25%      120.000000     80.000000      1.000000      1.000000      0.000000   
50%      120.000000     80.000000      1.000000      1.000000      0.000000   
75%      140.000000     90.000000      2.000000      1.000000      0.000000   
max    16020.000000  11000.000000      3.000000      3.000000      1.000000   

               alco        active        cardio        newage  
count  69999.000000  70000.000000  70000.000000  70000.000000  
mean       0.053772      0.803729      0.499700     70.270343  
std        0.225569      0.397179      0.500003      6.762064  
min        0.000000      0.000000      0.000000     59.000000  
25%        0.000000      1.000000      0.000000     65.000000  
50%        0.000000      1.000000      0.000000     70.000000  
75%        0.000000      1.000000      1.000000     75.000000  
max        1.000000      1.000000      1.000000     94.000000

In [6]:
df.shape

(70000, 14)

In [7]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           1
active         0
cardio         0
newage         0
dtype: int64

In [8]:
df.tail()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
69995  99993  19240       2     168    76.0    120     80            1     1   
69996  99995  22601       1     158   126.0    140     90            2     2   
69997  99996  19066       2     183   105.0    180     90            3     1   
69998  99998  22431       1     163    72.0    135     80            1     2   
69999  99999  20540       1     170    72.0    120     80            2     1   

       smoke  alco  active  cardio  newage  
69995      1   0.0       1       0      71  
69996      0   0.0       1       1      62  
69997      0   1.0       0       1      71  
69998      0   0.0       0       1      62  
69999      0   0.0       1       0      67

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
newage         0
dtype: int64

In [11]:
df.dtypes

id               int64
age              int64
gender           int64
height           int64
weight         float64
ap_hi            int64
ap_lo            int64
cholesterol      int64
gluc             int64
smoke            int64
alco           float64
active           int64
cardio           int64
newage           int64
dtype: object

In [12]:
df.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio', 'newage'],
      dtype='object')

In [13]:
df.drop('age',axis=1,inplace=True)

In [14]:
x=df.drop(['cardio'],axis=1)
y=df['cardio']

In [15]:
x.head()

id  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0   0       2     168    62.0    110     80            1     1      0   0.0   
1   1       1     156    85.0    140     90            3     1      0   0.0   
2   2       1     165    64.0    130     70            3     1      0   0.0   
3   3       2     169    82.0    150    100            1     1      0   0.0   
4   4       1     156    56.0    100     60            1     1      0   0.0   

   active  newage  
0       1      73  
1       1      68  
2       0      72  
3       1      75  
4       0      76

In [16]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: cardio, dtype: int64

In [17]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
x_train.shape

(55999, 12)

In [19]:
x_test.shape

(14000, 12)

In [20]:
x_test.head()

id  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
57622  82242       2     166    93.0    150     90            1     2      0   
39560  56523       2     173    70.0    120     80            1     1      1   
41416  59185       1     151    90.0    130     80            1     1      0   
47732  68154       2     172    91.0    130     80            3     1      0   
64802  92497       2     197    78.0    120     70            1     1      0   

       alco  active  newage  
57622   0.0       1      83  
39560   0.0       1      70  
41416   0.0       1      60  
47732   0.0       0      68  
64802   0.0       0      65

In [21]:
logmodel = LogisticRegression()

In [22]:
logmodel.fit(x_train,y_train)

LogisticRegression()

In [23]:
logmodelpred = logmodel.predict(x_test)

In [24]:
logmodelpred[:10]

array([1, 0, 1, 1, 0, 1, 0, 0, 1, 1], dtype=int64)

In [25]:
accuracy = accuracy_score(y_test,logmodelpred)*100

In [26]:
accuracy

70.59285714285714

In [27]:
dtc = DecisionTreeClassifier()

In [28]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [29]:
dtcpred=dtc.predict(x_test)

In [30]:
dtcpred[:10]

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

In [31]:
accuracy=accuracy_score(y_test,dtcpred)*100

In [32]:
accuracy

63.2

In [33]:
rfc=RandomForestClassifier()

In [34]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [35]:
rfcpred= rfc.predict(x_test)

In [36]:
rfcpred[:10]

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

In [37]:
accuracy=accuracy_score(y_test,rfcpred)*100

In [38]:
accuracy

71.62857142857143

In [39]:
df.head()

id  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0   0       2     168    62.0    110     80            1     1      0   0.0   
1   1       1     156    85.0    140     90            3     1      0   0.0   
2   2       1     165    64.0    130     70            3     1      0   0.0   
3   3       2     169    82.0    150    100            1     1      0   0.0   
4   4       1     156    56.0    100     60            1     1      0   0.0   

   active  cardio  newage  
0       1       0      73  
1       1       1      68  
2       0       1      72  
3       1       1      75  
4       0       0      76

In [40]:
x.head()

id  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0   0       2     168    62.0    110     80            1     1      0   0.0   
1   1       1     156    85.0    140     90            3     1      0   0.0   
2   2       1     165    64.0    130     70            3     1      0   0.0   
3   3       2     169    82.0    150    100            1     1      0   0.0   
4   4       1     156    56.0    100     60            1     1      0   0.0   

   active  newage  
0       1      73  
1       1      68  
2       0      72  
3       1      75  
4       0      76

In [41]:
new_input=[1, 1, 777, 72.0, 665, 70, 2, 2, 0, 0.0, 2, 53]

In [42]:
predictions=dtc.predict([new_input])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [43]:
accuracy

71.62857142857143